logging:
  file:
    name: myapp.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 10

application:
  bank:
    interestrate: 23
    interestrateIsInsuranceEnabled: 2
    interestrateIsSalaryClient: 1
    insurance: 50000

    employmentStatus:
      SELF_EMPLOYED: -1
      EMPLOYED: -1
      BUSINESS_OWNER: -2
    position:
      WORKER: -1
      MID_MANAGER: -2
      TOP_MANAGER: -3
      OWNER: 0
    maritalStatus:
      MARRIED: -1
      SINGLE: 1
    genderAndAgeRate:
      male30_55: -3
      female32_65: -3

